// <auto-generated />
using System;
using DebtDash.Web.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DebtDash.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DebtDashDbContext))]
    [Migration("20260306211045_InitialLoanTracker")]
    partial class InitialLoanTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DebtDash.Web.Domain.Models.LoanProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedMonthlyCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoanProfiles");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.PaymentLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalculatedRealRate")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysSincePreviousPayment")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FeesPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanProfileId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ManualRateOverride")
                        .HasColumnType("decimal(10,6)");

                    b.Property<bool>("ManualRateOverrideEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingBalanceAfterPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanProfileId", "PaymentDate");

                    b.ToTable("PaymentLogEntries");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.ProjectionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AsOfPaymentLogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaselineRemainingMonths")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeltaMonthsVsBaseline")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("LoanProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PredictedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrincipalVelocity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RemainingMonthsEstimate")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanProfileId");

                    b.ToTable("ProjectionSnapshots");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.RateVarianceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalculatedRate")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaymentLogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StatedOrOverrideRate")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("ThresholdBasisPoints")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("VarianceAbsolute")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("VarianceBasisPoints")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentLogEntryId")
                        .IsUnique();

                    b.ToTable("RateVarianceRecords");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.PaymentLogEntry", b =>
                {
                    b.HasOne("DebtDash.Web.Domain.Models.LoanProfile", "LoanProfile")
                        .WithMany("Payments")
                        .HasForeignKey("LoanProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanProfile");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.ProjectionSnapshot", b =>
                {
                    b.HasOne("DebtDash.Web.Domain.Models.LoanProfile", "LoanProfile")
                        .WithMany("Projections")
                        .HasForeignKey("LoanProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanProfile");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.RateVarianceRecord", b =>
                {
                    b.HasOne("DebtDash.Web.Domain.Models.PaymentLogEntry", "PaymentLogEntry")
                        .WithOne("RateVariance")
                        .HasForeignKey("DebtDash.Web.Domain.Models.RateVarianceRecord", "PaymentLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentLogEntry");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.LoanProfile", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Projections");
                });

            modelBuilder.Entity("DebtDash.Web.Domain.Models.PaymentLogEntry", b =>
                {
                    b.Navigation("RateVariance");
                });
#pragma warning restore 612, 618
        }
    }
}
